### ISSUE TITLE
MITgcm error when reading in float file 

### ISSUE THREAD

**Issue by nathanieltarshish** [rabernat/floater#20] opened 2016-12-07 15:45 UTC
I am encountering an error when running the MITgcm that appears in the .e file for the job I submitted to my cluster (not in STDERR or STDOUT):
```
In source file mdsio_rd_rec_rl.f, at line number 1824
 at line number 1824
 File name = flt_CM2p6_global_hex.bin    unformatted, direct access   record = 37172161
 In source file mdsio_rd_rec_rl.f, at line number 1824
PGFIO-F-253/unformatted read/unit=9/attempt to read non-existent record (direct access).
 File name = flt_CM2p6_global_hex.bin    unformatted
```
The relevant section with line 1824 is shown below: 
 ```fortran
      IF ( debugLevel.GE.debLevC ) THEN
        WRITE(msgBuf,'(A,I9,2x,I9)')
     &      ' MDS_RD_REC_RL: iRec,Dim = ', iRec, nArr
        CALL PRINT_MESSAGE( msgBuf, standardMessageUnit,
     &                      SQUEEZE_RIGHT , myThid )
      ENDIF

      IF ( fPrec.EQ.precFloat32 ) THEN
        READ( dUnit, rec=iRec ) r4Buf <--------------------------------- LINE 1824 
        DO k=1,nArr
          arr(k) = r4Buf(k)
        ENDDO
      ELSEIF ( fPrec.EQ.precFloat64 ) THEN
        READ( dUnit, rec=iRec ) r8Buf
        DO k=1,nArr
          arr(k) = r8Buf(k)
        ENDDO
      ELSE
        WRITE(msgBuf,'(A,I9)')
     &        ' MDS_RD_REC_RL: illegal value for fPrec=',fPrec
        CALL PRINT_ERROR( msgBuf, myThid )
        STOP 'ABNORMAL END: S/R MDS_RD_REC_RL'
      ENDIF

      RETURN
      END
```
The float file I am attempting to use was generated with
```python 

fs = generators.FloatSet((-280,80), (-81,65.0), dx=.03125, dy=.03125)
model_grid = {'lon': mask_lon, 'lat': mask_lat, 'land_mask': mask_bath}
fs.to_mitgcm_format("flt_CM2p6_global_hex", model_grid=model_grid)
```
From visually inspection, I am fairly confident that the hexagonal tiling step is done correctly. However, given the recent changes to `to_mitgcm_format()` it is possible that the output formatting was broken. To test this, I will try to rebuild a float file with the new code that I know was previously working fine with the MITgcm.

**Comment by rabernat** [comment] 2016-12-07 15:54
It sounds like MITgcm is expecting more float records than it found. As a quick check, see that the size of the file is consistent with the number of floats in your floatset.

FYI, MITgcm knows nothing about hexgrids or any of that. It simply reads a table of float initial positions. The format of this table is described in the ``to_migcm_format()`` function.

The logic of determining how many floats there are is here:
https://github.com/rabernat/floater/blob/master/floater/generators.py#L233

I would dig into that.

**Comment by nathanieltarshish** [comment] 2016-12-07 16:04
Okay, thanks for info. The file is of size 1.3G which seems roughly consistent with my expectations. I will look into that logic, which changed after the recent PR #14.

**Comment by rabernat** [comment] 2016-12-07 17:01
You can be exact though. The number of bytes should exactly match the number of records + 1

**Comment by nathanieltarshish** [comment] 2016-12-07 17:26
Not sure what you mean by the number of records. I have that `N = 37171843` floats and the size of the file is `1338186384 Bytes`. Does that check out?

**Comment by nathanieltarshish** [comment] 2016-12-07 18:01
I tried to recreate the float file from the verification run I got from you, which I inferred from the post-processing script was of the form:
```python
fs = generators.FloatSet((180,230), (-80,80), 1/32., 1/32.)
fs.to_mitgcm_format("flt_32deg_verification", mesh="hex")
```
I replaced the existing float file in the verification input folder with this new one and reran the MITgcm. This worked fortunately with no errors. So it seems that I did not universally break `to_migcm_format()` with PR #14!

**Comment by rabernat** [comment] 2016-12-07 19:20
37171844 / (9 records per float) / (4 bytes per record) - 1 == 37171843

Looks good.

**Comment by rabernat** [comment] 2016-12-07 20:39
@nathanieltarshish I think the solution is pretty simple. You have an inconsistency between the name of the file you are outputting with ``fs.to_mitgcm_format("flt_CM2p6_global_hex")`` and the input file in your ``data.flt`` file (which I assume is ``flt_CM2p6_global_hex.bin``). You just need to add (or remove) `.bin` from one of them.

**Comment by nathanieltarshish** [comment] 2016-12-08 14:21
@rabernat  That is true, but I manually appended the `.bin` extension to the file before running the simulation so I don't believe that is the error. Thanks though.

**Comment by rabernat** [comment] 2016-12-08 14:49
Well I am stuck then. @anirban89, do you have any thoughts?

**Comment by rabernat** [comment] 2016-12-08 14:52
number of actual float records: 37172161
error comes on record number: 37171843

What could be going on here.

**Comment by rabernat** [comment] 2016-12-08 14:53
Could you also post the tail of STDOUT.0000 and STDERR.0000?

**Comment by nathanieltarshish** [comment] 2016-12-08 15:37
So the deal with this:
``` 
number of actual float records: 37171843
error comes on record number: 37172161
```
( BTW I think you flipped the numbers by accident in your above post) 

There is a mistake I made wrapped up in this. Initially, I ran a simulation with a float file that was rectangularly tiled by accident. Then, I realized my mistake and generated the true hexagonal grid that has `N = 37171843 floats` . The error message in the original post was take by accident from the erroneously rectangularly tiled test. Sorry for botching that up and generating confusion.  

The true error corresponding to the test with the hexagonal grid that has `N = 37171843 floats` is 
```
In source file mdsio_rd_rec_rl.f, at line number 1824
PGFIO-F-253/unformatted read/unit=9/attempt to read non-existent record (direct access).
 File name = flt_CM2p6_global_hex.bin    unformatted, direct access   record = 37171845
```
The STDERR.* and  STDOUT.* are blank. The errors appear in the .e file for the job I submit to the cluster.  

Quick question: when I compiled `mitgcmuv` to work with CM2p6 I did not make any changes concerning float information (like to FLT.h). Did I perhaps overlooks something?

**Comment by rabernat** [comment] 2016-12-08 15:48
How can STDOUT and STDERR be blank?!? That will make debugging very hard...

**Comment by rabernat** [comment] 2016-12-08 16:00
We are looking for a line like this in STDOUT.0000:

```
(PID.TID 0000.0001)  bi,bj=   0   0 , npart,max_npart= 8.19200000E+06 8.19200000E+06
```

**Comment by nathanieltarshish** [comment] 2016-12-08 16:02
Okay, good to know. I am investigating what is going on with STDOUT and STDERR.

**Comment by nathanieltarshish** [comment] 2016-12-08 16:12
Seems like it may have to do with the output to STDOUT and STDERR being delayed due to buffering and then never actually written due to the program terminating. See this [MITgcm-support thread](http://mitgcm.org/pipermail/mitgcm-support/2007-February/004618.html)

**Comment by rabernat** [comment] 2016-12-08 16:17
Ok, well that makes it much harder to see what is going on. Basically, the model is expecting a different amount of floats than it is getting, but we can't know how many it is expecting because we can't see STDOUT.

I would have a look at ``flt_init_varia.F`` from lines 115-162. This is the code for reading the input file. Maybe you can look at it and try to see what is going on.

You could try with smaller / simpler float sets.

@anirban89 please weigh in with your opinion. Have you every encountered this error?

**Comment by rabernat** [comment] 2016-12-08 16:21
Another debugging step you could try is to (temporarily) add `print(N)` in ``to_mitgcm_format()``

https://github.com/rabernat/floater/blob/master/floater/generators.py#L233

**Comment by nathanieltarshish** [comment] 2016-12-08 16:27
> Another debugging step you could try is to (temporarily) add print(N) in to_mitgcm_format()

Yep. That is how I got the `N` values I cite in this thread. 

> I would have a look at flt_init_varia.F from lines 115-162. This is the code for reading the input file. Maybe you can look at it and try to see what is going on.

Will do.

**Comment by nathanieltarshish** [comment] 2016-12-08 17:49
Fixed the STDOUT and STDERR issue by adding the line `debugMode=.TRUE.` in the file `eedata`. Fetching the STDOUT file now.

**Comment by anirban89** [comment] 2016-12-08 18:35
Have you tried to generate the floats without using to_mit_gcm?
 Run a diff a nd see if they are different.

**Comment by nathanieltarshish** [comment] 2016-12-08 22:15
@rabernat Here is I think the relevant section of STDOUT.0000 that you asked for:
```fortran
(PID.TID 0000.0001)  MDS_READVEC_LOC: open file: flt_CM2p6_hex_32deg.bin
(PID.TID 0000.0001)  MDS_RD_REC_RL: iRec,Dim =         1          9
(PID.TID 0000.0001)  bi,bj=   0   0 , npart,max_npart= 3.71718440E+07 3.71718440E+07
(PID.TID 0000.0001)  MDS_RD_REC_RL: iRec,Dim =         2          9
(PID.TID 0000.0001)  MDS_RD_REC_RL: iRec,Dim =         3          9
(PID.TID 0000.0001)  MDS_RD_REC_RL: iRec,Dim =         4          9
(PID.TID 0000.0001)  MDS_RD_REC_RL: iRec,Dim =         5          9
``` 

@anirban89 
Thanks for the suggestion. Not sure I totally follow though. 
> Have you tried to generate the floats without using to_mit_gcm

Are you suggesting that I call `get_oceancoords` on its own and then compare to the output of `to_mit_gcm` (which calls  `get_oceancoords` itself) ? Given the different formats, I'm not sure how informative a diff would be. Or am I misinterpreting your suggestion? Thanks

**Comment by rabernat** [comment] 2016-12-09 00:26
Ok we are getting somewhere. From reading the record  of the binary file. MITgcm is saying that.
```
npart = 37171844
```
This is the number of floats it expects to find.

You are saying that
```
N = 37171843 
```

So they differ by one. This is the source of the problem.

You should check the binary file directly to verify whether the correct npart (37171843) is actually in the file. This should be the first value of the first record. It is written by floater here:
https://github.com/rabernat/floater/blob/master/floater/generators.py#L260
And read by MITgcm here (line 126):
http://mitgcm.org/viewvc/MITgcm/MITgcm/pkg/flt/flt_init_varia.F?revision=1.11&view=markup

You can load the binary file from python using ``np.fromfile``. You can see the test for an example of how to read it:
https://github.com/rabernat/floater/blob/master/floater/test/test_generators.py#L108

**Comment by rabernat** [comment] 2016-12-09 00:36
Btw, I this whole time I have been assuming you understand how the float file is formatted. But this is probably not the case. Let me spell it out clearly. This is not really documented anywhere but inside the MITgcm code.

The float input file is a raw binary file of floating point numbers of either 32- or 64-bit precision, depending on the the value of `readBinaryPrec` in the `data` file. (In our case, we are using 32-bit.) MITgcm always expects big-endian data. In python, the datatype can be encoded as ``np.dtype('>f4').

 The size of the file is (N + 1 )*9, where N is the total number of floats. You can think of this as representing a table of N+1 rows and 9 columns. The columns contain the information about the float initial positions. These are encoded here:
https://github.com/rabernat/floater/blob/master/floater/generators.py#L239

The *first* row of the file is special. It is a "header". It tells MITgcm how many records to expect in the file. (This is an old-fashioned way of encoding metadata.) I don't think all 9 columns of the header are used, just the first and the sixth. These contain the total number of floats and the maximum allowable number of floats. I don't understand the difference between these two parameters, and I always set them to be the same:
https://github.com/rabernat/floater/blob/master/floater/generators.py#L260

**Comment by anirban89** [comment] 2016-12-09 01:36
I meant to generate the float input dataset without using the to_mitgcm function and see if it breaks or try the test

**Comment by rabernat** [comment] 2016-12-09 01:45
> I meant to generate the float input dataset without using the to_mitgcm function and see if it breaks or try the test

I don't think that Nathaniel knows how to do that. He is relying on the function.

**Comment by nathanieltarshish** [comment] 2016-12-09 03:33
@rabernat Thanks very much for the detailed overview of the float file format. Was very informative and is something that I think would be nice to eventually include in the floater documentation. 

It looks like `npart = 37171844` in the binary file:
```python
In [2]: array = np.fromfile('flt_CM2p6_hex_32deg.bin', dtype='>f4')
In [3]: np.shape(array)
Out[3]: (334546596,)
In [4]: array[0]
Out[4]: 37171844.0
```
So I went back to the float file generator and put these print statements into generators.py:
```python
        # copied from Andreas
        flt_matrix[0,0] = N;
        flt_matrix[0,1] = -1
        flt_matrix[0,4] = -1
        flt_matrix[0,5] = N
        flt_matrix[0,8] = -1

        print "N = ", N  
        print "flt_matrix[0,0] = " "%.16f" % flt_matrix[0,0]

        #fname = os.path.join(output_dir, output_fname)
        return flt_matrix.tofile(filename)
```
which after running output:
```string
N =  37171843
flt_matrix[0,0] = 37171844.0000000000000000
```
Holy mother of pearl! What is going on here?

**Comment by rabernat** [comment] 2016-12-09 03:52
Ok wow. This is officially weird.

**Comment by rabernat** [comment] 2016-12-09 03:56
It could be a type conversion error.

Here's what I suggest. Create a new pull request to add this check to ``test/test_generators.py`` inside the ``test_to_mitgcm_format`` function: https://github.com/rabernat/floater/blob/master/floater/test/test_generators.py#L108

It's basically two lines:
```python
npart = fs.Nx*fs.Ny
assert int(array[0]) == npart
```

Let's see if that passes for our test cases. I think that will be informative.

**Comment by nathanieltarshish** [comment] 2016-12-09 14:25
> Let's see if that passes for our test cases. I think that will be informative.

Submitted this as PR #22 which looks like it passed. I should note that in `to_mitgcm_format()`, we have 
`N = len(lon)` instead of `N = fs.Nx*fs.Ny`. I'll submit another test where I make `N` a class attribute of `FloatSet` and test with
```python
npart = fs.N
assert int(array[0]) == npart
```

**Comment by nathanieltarshish** [comment] 2016-12-09 14:48
> I'll submit another test where I make `N` a class attribute of FloatSet

Submitted again in PR #22 which just passed again. Perhaps the type conversion error only occurs at large `N` (i.e. depends on the number of bits)? In the test cases, the largest is `N=250000` and the known bug case is two orders of magnitude larger with `N= 37171844`.

**Comment by rabernat** [comment] 2016-12-09 15:00
The test cases don't have any masks. That might be part of the problem.

**Comment by nathanieltarshish** [comment] 2016-12-09 16:17
I agree that it looks like the bug is related to masks: 
```python 
fs = generators.FloatSet((-280,80), (-81,65.0), dx=.03125, dy=.03125)
fs.to_mitgcm_format("bug_check",model_grid=model_grid, mesh="rect")
```
which returns
```
N =  37172159
flt_matrix[0,0] = 37172160.0000000000000000
```
while
```python
fs.to_mitgcm_format("bug_check", mesh="rect")
```
returns 
```
N =  53821440
flt_matrix[0,0] = 53821440.0000000000000000
```

**Comment by rabernat** [comment] 2016-12-09 17:30
@nathanieltarshish: in #23 I added testing of land masks with ``to_mitgcm_format()``. I can't reproduce this error with any of the examples. So that helps us narrow it down.

Once you review my PR, we can merge it and you can try with my updated code. Maybe some of the changes I made will fix this issue.

**Comment by nathanieltarshish** [comment] 2016-12-09 18:03
@rabernat I reviewed and improved the PR #23. To help narrow it down, I went hunting for a more "minimal" example that did not involve using the CM2p6 land mask. Here is a configuration I found that reproduces the error:

```python
fs = generators.FloatSet((0.0, 180.0), (-80.0,80.0), dx=1/32., dy=1/32.)

#mask grid resolution is five times as coarse as the float set
Nx = int((fs.xlim[1] - fs.xlim[0]) / fs.dx)/5
Ny = int((fs.ylim[1] - fs.ylim[0]) / fs.dy)/5
lon = np.linspace(fs.xlim[0], fs.xlim[1], Nx)
lat = np.linspace(fs.ylim[0], fs.ylim[1], Ny)

#set entire domain to ocean
mask = np.ones((Ny, Nx), dtype='bool')

#make a small land island 
mask[5:10,5:10] = False 

model_grid = {'lon': lon, 'lat': lat, 'land_mask': mask}
fs.to_mitgcm_format("bug_check", model_grid=model_grid, mesh="rect")
```
the print statements output:
```
N =  29490575
flt_matrix[0,0] = 29490576.0000000000000000
```

**Comment by rabernat** [comment] 2016-12-09 18:07
Do you also get the error if you make the land the whole northern half of the domain, as is in the test cases? i.e.
```python
mask[Ny/2:] = False 
```

**Comment by nathanieltarshish** [comment] 2016-12-09 18:13
I should emphasis that I am still working with the pre-PR #23. code. Just checked the half the domain is land case and there was no error: 
```
N =  14745600
flt_matrix[0,0] = 14745600.0000000000000000
```
I will now repeat the tests with the new post-PR #23 code.

**Comment by rabernat** [comment] 2016-12-09 18:16
What I am getting at is that I want to include this example in the tests. That is not possible with the way the tests are currently structured, because there is no way to make your "island". That can be changed of course by refactoring the tests further.

**Comment by nathanieltarshish** [comment] 2016-12-09 18:38
FYI I redid the test with the post-PR #23 code:
```python
xlim = (0.0, 180.0)
ylim = (-80.0,80.0)
dx = 1/32.
dy = 1/32.

#mask grid resolution is five times as coarse as the float set
Nx = int((xlim[1] - xlim[0]) / dx)/5
Ny = int((ylim[1] - ylim[0]) / dy)/5
lon = np.linspace(xlim[0], xlim[1], Nx)
lat = np.linspace(ylim[0], ylim[1], Ny)

#set entire domain to ocean
mask = np.ones((Ny, Nx), dtype='bool')

#make a small land island 
mask[5:10,5:10] = False 

model_grid = {'lon': lon, 'lat': lat, 'land_mask': mask}
fs = generators.FloatSet(xlim, ylim, dx, dy, model_grid=model_grid)
fs.to_mitgcm_format("bug_check", mesh="rect")
```
outputs with the error:
```
N =  29490575
flt_matrix[0,0] = 29490576.0000000000000000
```
Small changes to virtually any of the above parameters makes the bug disappears. For instance, moving the island to `mask[6:10,5:10] = False ` makes it vanish. Basically any change that produces a change in N. 

My guess is that the error only depends on the value of N. So how I build the land mask is not essential to reproducing the error. I am going to hunt for an example configuration in which the error occurs with the current test case mask: `mask[Ny/2:] = False `.

**Comment by nathanieltarshish** [comment] 2016-12-09 18:47
I should have thought of this earlier. Ran this code totally independent of floater: 
```python
N = 29490575
output_dtype = np.dtype('>f4')
flt_matrix = np.zeros((N+1,9), dtype=output_dtype)
flt_matrix[0,0] = N;
print "N = ", N  
print "flt_matrix[0,0] = " "%.16f" % flt_matrix[0,0]
```
which returns the error. I am going to experiment to find which values of N this happens to.

**Comment by nathanieltarshish** [comment] 2016-12-09 20:11
It is a type conversion error that occurs at large N: specifically, the error first occurs at ``N = 16777217``. The code 
```python
N = 16777217
N_to_f4 = np.array([N], dtype='>f4') 
print N_to_f4
```
will return `[ 16777216.]` .   I guess `dtype='>f4'` does not have enough memory to store `N` exactly.  By looping through N, I got a sense of how the error occurrence grows:
<img width="426" alt="error_occurence" src="https://cloud.githubusercontent.com/assets/20796154/21062934/1cdd552a-be21-11e6-9057-d5add401269e.png">

For example, numbers in the general neighborhood of CMp6's `N = 29490575` that are odd will converted to even numbers.

**Comment by nathanieltarshish** [comment] 2016-12-09 20:33
[Here](http://stackoverflow.com/questions/15094611/behavior-of-float-that-is-used-as-an-integer) is an explanation of why 16777216 is the last exactly representable number in 32-bit binary floating point precision.

**Comment by rabernat** [comment] 2016-12-09 20:56
Just drilling down on this more. Seems like a numpy bug to me!

```python
N = 29490575
np.array(N, dtype='f8')
>>> array(29490575.0)
np.array(N, dtype='f8').astype('f4')
>>> array(29490576.0, dtype=float32)
```

This is a crazy way to do type conversion.

**Comment by rabernat** [comment] 2016-12-09 21:02
I posted my comment before refreshing and seeing that you had dug much deeper.

**Comment by rabernat** [comment] 2016-12-09 23:05
Let's just use 64 bit precision.

**Closed** 2016-12-19 16:50 UTC
